openapi: 3.2.0
info:
  title: Evrim Transform API
  version: 0.5.18
  description: Data when and how you want it.
tags:
- name: Transform
paths:
  /prod/v0/transform/profile/{profile_id}/latest/:
    get:
      operationId: transform_profile_latest_retrieve
      description: Transform a profile snapshot into a tabular format
      parameters:
      - in: path
        name: profile_id
        schema:
          type: integer
        required: true
      tags:
      - Transform
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
      summary: Transform profile latest retrieve
      x-summary-source: derived
components:
  securitySchemes:
    knoxApiToken:
      type: http
      scheme: bearer
