openapi: 3.2.0
info:
  title: Evrim Health API
  version: 0.5.18
  description: Data when and how you want it.
tags:
- name: Health
paths:
  /prod/v0/health/profile/{profile_id}/latest/:
    get:
      operationId: health_profile_latest_retrieve
      description: Get the latest snapshot health for a profile
      parameters:
      - in: path
        name: profile_id
        schema:
          type: integer
        required: true
      tags:
      - Health
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
      summary: Health profile latest retrieve
      x-summary-source: derived
  /prod/v0/health/snapshot/{snapshot_id}/:
    get:
      operationId: health_snapshot_retrieve
      description: Get the health of a profile snapshot
      parameters:
      - in: path
        name: snapshot_id
        schema:
          type: integer
        required: true
      tags:
      - Health
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
      summary: Health snapshot retrieve
      x-summary-source: derived
components:
  securitySchemes:
    knoxApiToken:
      type: http
      scheme: bearer
