openapi: 3.0.3
info:
  title: Evrim answers questions API
  version: 0.5.18
  description: Data when and how you want it.
tags:
- name: questions
paths:
  /prod/v0/questions/:
    get:
      operationId: questions_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - questions
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedQuestionList'
          description: ''
components:
  schemas:
    Question:
      type: object
      properties:
        question:
          type: string
          maxLength: 255
      required:
      - question
    PaginatedQuestionList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Question'
  securitySchemes:
    knoxApiToken:
      type: http
      scheme: bearer
