openapi: 3.2.0
info:
  title: Evrim Fields API
  version: 0.5.18
  description: Data when and how you want it.
tags:
- name: Fields
paths:
  /prod/v0/fields/:
    get:
      operationId: fields_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: type
        schema:
          type: string
          enum:
          - bln
          - enm
          - flt
          - int
          - rel
          - str
        description: '* `str` - String

          * `int` - Integer

          * `flt` - Float

          * `bln` - Boolean

          * `rel` - Relationship

          * `enm` - Enum'
      tags:
      - Fields
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedFieldList'
          description: ''
      summary: Fields list
      x-summary-source: derived
    post:
      operationId: fields_create
      tags:
      - Fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Field'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Field'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Field'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
      summary: Fields create
      x-summary-source: derived
  /prod/v0/fields/{field_id}/template/:
    post:
      operationId: fields_template_create
      parameters:
      - in: path
        name: field_id
        schema:
          type: string
          pattern: ^\d+$
        required: true
      tags:
      - Fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldToTemplate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FieldToTemplate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FieldToTemplate'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldToTemplate'
          description: ''
      summary: Fields template create
      x-summary-source: derived
  /prod/v0/fields/{id}/:
    get:
      operationId: fields_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - Fields
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
      summary: Fields retrieve
      x-summary-source: derived
    put:
      operationId: fields_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - Fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Field'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Field'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Field'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
      summary: Fields update
      x-summary-source: derived
    patch:
      operationId: fields_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - Fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedField'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedField'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedField'
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
      summary: Fields partial update
      x-summary-source: derived
    delete:
      operationId: fields_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - Fields
      security:
      - knoxApiToken: []
      responses:
        '204':
          description: No response body
      summary: Fields destroy
      x-summary-source: derived
components:
  schemas:
    PatchedField:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 255
        type:
          type: string
          maxLength: 3
        rel_template_id:
          type:
          - integer
          - 'null'
          writeOnly: true
        rel_template:
          type:
          - integer
          - 'null'
          readOnly: true
        enum_values:
          type: array
          items:
            type: string
            maxLength: 255
        enum_many:
          type: boolean
        sources:
          type:
          - array
          - 'null'
          items:
            type: string
            maxLength: 255
        directed:
          type: boolean
          default: false
        keyword_search:
          type: boolean
          default: true
        raw_documents:
          type: boolean
          default: false
    FieldToTemplate:
      type: object
      properties:
        template_id:
          type: integer
          writeOnly: true
      required:
      - template_id
    Field:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 255
        type:
          type: string
          maxLength: 3
        rel_template_id:
          type:
          - integer
          - 'null'
          writeOnly: true
        rel_template:
          type:
          - integer
          - 'null'
          readOnly: true
        enum_values:
          type: array
          items:
            type: string
            maxLength: 255
        enum_many:
          type: boolean
        sources:
          type:
          - array
          - 'null'
          items:
            type: string
            maxLength: 255
        directed:
          type: boolean
          default: false
        keyword_search:
          type: boolean
          default: true
        raw_documents:
          type: boolean
          default: false
      required:
      - description
      - name
      - rel_template
      - type
    PaginatedFieldList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Field'
  securitySchemes:
    knoxApiToken:
      type: http
      scheme: bearer
