openapi: 3.2.0
info:
  title: Evrim Tags API
  version: 0.5.18
  description: Data when and how you want it.
tags:
- name: Tags
paths:
  /prod/v0/tags/:
    get:
      operationId: tags_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - Tags
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTagList'
          description: ''
      summary: Tags list
      x-summary-source: derived
    post:
      operationId: tags_create
      tags:
      - Tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      summary: Tags create
      x-summary-source: derived
  /prod/v0/tags/{id}/:
    get:
      operationId: tags_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - Tags
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      summary: Tags retrieve
      x-summary-source: derived
    put:
      operationId: tags_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - Tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      summary: Tags update
      x-summary-source: derived
    patch:
      operationId: tags_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - Tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTag'
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      summary: Tags partial update
      x-summary-source: derived
    delete:
      operationId: tags_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - Tags
      security:
      - knoxApiToken: []
      responses:
        '204':
          description: No response body
      summary: Tags destroy
      x-summary-source: derived
  /prod/v0/tags/{tag_id}/collections/:
    post:
      operationId: tags_collections_create
      description: Tag a collection
      parameters:
      - in: path
        name: tag_id
        schema:
          type: string
          pattern: ^\d+$
        required: true
      tags:
      - Tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagToCollection'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TagToCollection'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TagToCollection'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagToCollection'
          description: ''
      summary: Tags collections create
      x-summary-source: derived
  /prod/v0/tags/{tag_id}/profiles/:
    get:
      operationId: tags_profiles_list
      description: Get all profiles associated with a tag
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: path
        name: tag_id
        schema:
          type: string
          pattern: ^\d+$
        required: true
      tags:
      - Tags
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProfileList'
          description: ''
      summary: Tags profiles list
      x-summary-source: derived
    post:
      operationId: tags_profiles_create
      description: Tag all profiles with the tag
      parameters:
      - in: path
        name: tag_id
        schema:
          type: string
          pattern: ^\d+$
        required: true
      tags:
      - Tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagProfiles'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TagProfiles'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TagProfiles'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          description: No response body
      summary: Tags profiles create
      x-summary-source: derived
components:
  schemas:
    Template:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type:
          - string
          - 'null'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        questions:
          type: array
          items:
            type: string
            maxLength: 255
      required:
      - fields
      - id
      - name
    Tag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type:
          - string
          - 'null'
      required:
      - id
      - name
    Snapshot:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        status:
          type: string
          readOnly: true
          maxLength: 1
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
          readOnly: true
        fields:
          type: array
          items:
            $ref: '#/components/schemas/CreatedField'
          readOnly: true
        reports:
          type: array
          items:
            $ref: '#/components/schemas/Report'
          readOnly: true
      required:
      - answers
      - fields
      - id
      - reports
      - status
    CreatedField:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          writeOnly: true
          maxLength: 255
        specification:
          type: string
          writeOnly: true
          maxLength: 255
        source_entity_type:
          type:
          - string
          - 'null'
          writeOnly: true
          maxLength: 255
        description:
          type: string
          writeOnly: true
          maxLength: 255
        type:
          type: string
          writeOnly: true
          maxLength: 3
        enum_values:
          type: array
          items:
            type: string
            maxLength: 255
          writeOnly: true
        enum_many:
          type: boolean
          writeOnly: true
        rel_template:
          allOf:
          - $ref: '#/components/schemas/Template'
          writeOnly: true
        field:
          allOf:
          - $ref: '#/components/schemas/Field'
          readOnly: true
        status:
          type: string
          readOnly: true
          maxLength: 1
        value:
          readOnly: true
        sources:
          type:
          - array
          - 'null'
          items:
            type: string
            maxLength: 255
          writeOnly: true
        directed_source:
          type:
          - string
          - 'null'
          writeOnly: true
          maxLength: 255
        keyword_search:
          type:
          - boolean
          - 'null'
        raw_documents:
          type:
          - boolean
          - 'null'
      required:
      - description
      - field
      - id
      - name
      - specification
      - status
      - type
      - value
    Report:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        profile_id:
          type: integer
          writeOnly: true
        outline_id:
          type: integer
          writeOnly: true
        outline:
          allOf:
          - $ref: '#/components/schemas/Outline'
          readOnly: true
        report:
          readOnly: true
      required:
      - id
      - outline
      - outline_id
      - profile_id
      - report
    TagProfiles:
      type: object
      description: Add tag to all profiles
      properties:
        profile_ids:
          type: array
          items:
            type: integer
          writeOnly: true
      required:
      - profile_ids
    Outline:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        profile_id:
          type: integer
          writeOnly: true
        report_title:
          type: string
          writeOnly: true
          maxLength: 255
        section_titles:
          type: array
          items:
            type: string
            maxLength: 255
          writeOnly: true
        outline: {}
        perspective:
          type: string
          maxLength: 255
      required:
      - id
      - perspective
      - profile_id
      - report_title
      - section_titles
    Profile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        template_id:
          type: integer
          writeOnly: true
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        specification:
          type: string
          maxLength: 510
        source_map:
          writeOnly: true
        source:
          type: string
          writeOnly: true
          maxLength: 255
        template:
          allOf:
          - $ref: '#/components/schemas/Template'
          readOnly: true
        snapshots:
          type: array
          items:
            $ref: '#/components/schemas/Snapshot'
          readOnly: true
      required:
      - id
      - snapshots
      - specification
      - template
      - template_id
    PaginatedProfileList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Profile'
    Field:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 255
        type:
          type: string
          maxLength: 3
        rel_template_id:
          type:
          - integer
          - 'null'
          writeOnly: true
        rel_template:
          type:
          - integer
          - 'null'
          readOnly: true
        enum_values:
          type: array
          items:
            type: string
            maxLength: 255
        enum_many:
          type: boolean
        sources:
          type:
          - array
          - 'null'
          items:
            type: string
            maxLength: 255
        directed:
          type: boolean
          default: false
        keyword_search:
          type: boolean
          default: true
        raw_documents:
          type: boolean
          default: false
      required:
      - description
      - name
      - rel_template
      - type
    Answer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        answer:
          readOnly: true
        question:
          type: string
          readOnly: true
          maxLength: 510
        source:
          type:
          - string
          - 'null'
          maxLength: 510
      required:
      - answer
      - id
      - question
    PatchedTag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type:
          - string
          - 'null'
    PaginatedTagList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    TagToCollection:
      type: object
      description: Add all profiles with a specific tag to a collection
      properties:
        collection_id:
          type: integer
          writeOnly: true
      required:
      - collection_id
  securitySchemes:
    knoxApiToken:
      type: http
      scheme: bearer
