openapi: 3.0.3
info:
  title: Evrim answers fields API
  version: 0.5.18
  description: Data when and how you want it.
tags:
- name: fields
paths:
  /prod/v0/fields/:
    get:
      operationId: fields_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: type
        schema:
          type: string
          enum:
          - bln
          - enm
          - flt
          - int
          - rel
          - str
        description: '* `str` - String

          * `int` - Integer

          * `flt` - Float

          * `bln` - Boolean

          * `rel` - Relationship

          * `enm` - Enum'
      tags:
      - fields
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedFieldList'
          description: ''
    post:
      operationId: fields_create
      tags:
      - fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Field'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Field'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Field'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
  /prod/v0/fields/{field_id}/template/:
    post:
      operationId: fields_template_create
      parameters:
      - in: path
        name: field_id
        schema:
          type: string
          pattern: ^\d+$
        required: true
      tags:
      - fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldToTemplate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FieldToTemplate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FieldToTemplate'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldToTemplate'
          description: ''
  /prod/v0/fields/{id}/:
    get:
      operationId: fields_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - fields
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
    put:
      operationId: fields_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Field'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Field'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Field'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
    patch:
      operationId: fields_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedField'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedField'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedField'
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
          description: ''
    delete:
      operationId: fields_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this field.
        required: true
      tags:
      - fields
      security:
      - knoxApiToken: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    FieldToTemplate:
      type: object
      properties:
        template_id:
          type: integer
          writeOnly: true
      required:
      - template_id
    PaginatedFieldList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    Field:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 255
        type:
          type: string
          maxLength: 3
        rel_template_id:
          type: integer
          writeOnly: true
          nullable: true
        rel_template:
          type: integer
          readOnly: true
          nullable: true
        enum_values:
          type: array
          items:
            type: string
            maxLength: 255
        enum_many:
          type: boolean
        sources:
          type: array
          items:
            type: string
            maxLength: 255
          nullable: true
        directed:
          type: boolean
          default: false
        keyword_search:
          type: boolean
          default: true
        raw_documents:
          type: boolean
          default: false
      required:
      - description
      - name
      - rel_template
      - type
    PatchedField:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 255
        type:
          type: string
          maxLength: 3
        rel_template_id:
          type: integer
          writeOnly: true
          nullable: true
        rel_template:
          type: integer
          readOnly: true
          nullable: true
        enum_values:
          type: array
          items:
            type: string
            maxLength: 255
        enum_many:
          type: boolean
        sources:
          type: array
          items:
            type: string
            maxLength: 255
          nullable: true
        directed:
          type: boolean
          default: false
        keyword_search:
          type: boolean
          default: true
        raw_documents:
          type: boolean
          default: false
  securitySchemes:
    knoxApiToken:
      type: http
      scheme: bearer
